---
- name: Delete a Windows user
  hosts: 10.200.2.214
  gather_facts: true
  tasks:
    - name: Remove the Windows user
      ansible.windows.win_user:
        name: Sword   # Replace with the username you want to delete
        state: absent   # This ensures the user is deleted
