---
- name: Install Windows 11 using Windows 11 Installation Assistant
  hosts: 10.200.2.214  # Adjust to your target group or host
  gather_facts: yes

  tasks:
    - name: Download Windows 11 Installation Assistant
      win_get_url:
        url: https://go.microsoft.com/fwlink/?linkid=2171764  # URL for the Windows 11 Installation Assistant
        dest: C:\Temp\Windows11InstallationAssistant.exe

    - name: Run Windows 11 Installation Assistant
      win_command: C:\Temp\Windows11InstallationAssistant.exe /quiet /norestart
      register: install_result

    - name: Check if installation was successful
      debug:
        msg: "Windows 11 Installation Assistant ran successfully."
      when: install_result.rc == 0

    - name: Reboot the system if required
      ansible.windows.win_reboot:
        reboot_timeout: 600
        test_command: whoami
      when: install_result.rc == 0
