---
- name: Install Windows updates
  hosts: 10.200.2.214  # Replace with your Windows host
  gather_facts: yes
  tasks:
    - name: Install all available updates
      ansible.windows.win_updates:
        category_names:
          - "CriticalUpdates"
          - "SecurityUpdates"
          - "CumulativeUpdates"
        reboot: no  # Do not automatically reboot; handle it manually
        state: installed
      register: ansible_windows_update

    - name: Check if a reboot is required
      debug:
        msg: "Reboot required"
      when: ansible_windows_update.reboot_required | default(false)

    - name: Reboot the system if required
      ansible.windows.win_reboot:
        reboot_timeout: 600  # Set the timeout in seconds
        test_command: whoami  # Run 'whoami' to verify if the system is up after reboot
      when: ansible_windows_update.reboot_required | default(false)
