---
- name: Install Windows updates
  hosts: Windows11
  gather_facts: yes
  tasks:
    - name: Install all available updates
      ansible.windows.win_updates:
        category_names:
          - "CriticalUpdates"
          - "SecurityUpdates"
        reboot: no  # Do not automatically reboot; handle it manually
        state: installed
      register: ansible_windows_update

    - name: Reboot the system if required
      ansible.windows.win_reboot:
        reboot_timeout: 600
        test_command: whoami
      when: ansible_windows_update.reboot_required | default(false)
