---
- name: Update Windows 11 OS Version
  hosts: 10.200.2.214
  gather_facts: yes

  tasks:
    - name: Install all available updates (including feature updates)
      ansible.windows.win_updates:
        category_names:
          - "SecurityUpdates"
          - "CriticalUpdates"
          - "FeaturePacks"  # This category includes feature updates (OS version upgrades)
        reboot: no  # Do not reboot automatically, handle it manually
        state: installed
      register: update_result

    - name: Reboot if a reboot is required after the update
      ansible.windows.win_reboot:
        reboot_timeout: 600  # Set the timeout in seconds
        test_command: whoami  # Run 'whoami' to ensure the system is up after reboot
      when: update_result.reboot_required | default(false)
